# Generated by Django 6.1.1 on 2026-10-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cuentacontable_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacontable',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('', 'General'), ('activo_corriente', 'Activo corriente'), ('existencias', 'Existencias'), ('activo_no_corriente', 'Activo no corriente'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('gastos', 'Gastos'), ('ingresos', 'Ingresos'), ('costo_ventas', 'Costo de Ventas'), ('gasto_operativo', 'Gasto Operativo'), ('gasto_financiero', 'Gasto Financiero'), ('otro_ingreso', 'Otro Ingreso'), ('otro_gasto', 'Otro Gasto')], default='', max_length=20, verbose_name='Subcategoría'),
        ),
    ]
