"""Catálogo de clase. No incluye clases 8 y 9 ni cambia reglas de saldos.

Los tipos mantienen los valores internos en minúsculas del modelo.
60 conserva la agrupación costo_ventas usada por los cargadores anteriores.
29, 36 y 39 son activos: sus saldos acreedores restan del activo en el balance.
"""

# (código único, nombre, tipo, subcategoría)
PLAN_CUENTAS = (
    ('10', 'Efectivo y Equivalentes de Efectivo', 'activo', 'activo_corriente'),
    ('11', 'Inversiones Financieras', 'activo', 'activo_corriente'),
    ('12', 'Cuentas por Cobrar Comerciales – Terceros', 'activo', 'activo_corriente'),
    ('13', 'Cuentas por Cobrar Comerciales – Relacionadas', 'activo', 'activo_corriente'),
    ('14', 'Cuentas por Cobrar al Personal, a los Accionistas (Socios), Directores y Gerentes', 'activo', 'activo_corriente'),
    ('16', 'Cuentas por Cobrar Diversas – Terceros', 'activo', 'activo_corriente'),
    ('17', 'Cuentas por Cobrar Diversas – Relacionadas', 'activo', 'activo_corriente'),
    ('18', 'Servicios y Otros Contratados por Anticipado', 'activo', 'activo_corriente'),
    ('20', 'Mercaderías', 'activo', 'existencias'),
    ('21', 'Productos Terminados', 'activo', 'existencias'),
    ('22', 'Subproductos, Desechos y Desperdicios', 'activo', 'existencias'),
    ('23', 'Productos en Proceso', 'activo', 'existencias'),
    ('24', 'Materias Primas', 'activo', 'existencias'),
    ('25', 'Materiales Auxiliares, Suministros y Repuestos', 'activo', 'existencias'),
    ('26', 'Envases y Embalajes', 'activo', 'existencias'),
    ('27', 'Activos No Corrientes Mantenidos para la Venta', 'activo', 'activo_no_corriente'),
    ('28', 'Existencias por Recibir', 'activo', 'existencias'),
    ('29', 'Desvalorización de Existencias', 'activo', 'existencias'),
    ('30', 'Inversiones Mobiliarias', 'activo', 'activo_no_corriente'),
    ('31', 'Inversiones Inmobiliarias', 'activo', 'activo_no_corriente'),
    ('32', 'Activos Adquiridos en Arrendamiento Financiero', 'activo', 'activo_no_corriente'),
    ('33', 'Inmuebles, Maquinaria y Equipo', 'activo', 'activo_no_corriente'),
    ('34', 'Intangibles', 'activo', 'activo_no_corriente'),
    ('35', 'Activos Biológicos', 'activo', 'activo_no_corriente'),
    ('36', 'Desvalorización de Activo Inmovilizado', 'activo', 'activo_no_corriente'),
    ('37', 'Activo Diferido', 'activo', 'activo_no_corriente'),
    ('38', 'Otros Activos', 'activo', 'activo_no_corriente'),
    ('39', 'Depreciación, Amortización y Agotamiento Acumulados', 'activo', 'activo_no_corriente'),
    ('40', 'Tributos y Aportes al Sistema de Pensiones y de Salud por Pagar', 'pasivo', 'pasivo'),
    ('41', 'Remuneraciones y Participaciones por Pagar', 'pasivo', 'pasivo'),
    ('42', 'Cuentas por Pagar Comerciales – Terceros', 'pasivo', 'pasivo'),
    ('43', 'Cuentas por Pagar Comerciales – Relacionadas', 'pasivo', 'pasivo'),
    ('44', 'Cuentas por Pagar a los Accionistas, Directores y Gerentes', 'pasivo', 'pasivo'),
    ('45', 'Obligaciones Financieras', 'pasivo', 'pasivo'),
    ('46', 'Cuentas por Pagar Diversas – Terceros', 'pasivo', 'pasivo'),
    ('47', 'Cuentas por Pagar Diversas – Relacionadas', 'pasivo', 'pasivo'),
    ('48', 'Provisiones', 'pasivo', 'pasivo'),
    ('49', 'Pasivo Diferido', 'pasivo', 'pasivo'),
    ('50', 'Capital', 'patrimonio', 'patrimonio'),
    ('51', 'Acciones de Inversión', 'patrimonio', 'patrimonio'),
    ('52', 'Capital Adicional', 'patrimonio', 'patrimonio'),
    ('56', 'Resultados No Realizados', 'patrimonio', 'patrimonio'),
    ('57', 'Excedente de Revaluación', 'patrimonio', 'patrimonio'),
    ('58', 'Reservas', 'patrimonio', 'patrimonio'),
    ('60', 'Compras', 'gasto', 'costo_ventas'),
    ('61', 'Variación de Existencias', 'gasto', 'gastos'),
    ('62', 'Gastos de Personal, Directores y Gerentes', 'gasto', 'gastos'),
    ('63', 'Gastos de Servicios Prestados por Terceros', 'gasto', 'gastos'),
    ('64', 'Gastos por Tributos', 'gasto', 'gastos'),
    ('65', 'Otros Gastos de Gestión', 'gasto', 'gastos'),
    ('66', 'Pérdida por Medición de Activos No Financieros al Valor Razonable', 'gasto', 'otro_gasto'),
    ('67', 'Gastos Financieros', 'gasto', 'gasto_financiero'),
    ('68', 'Valuación y Deterioro de Activos y Provisiones', 'gasto', 'gastos'),
    ('69', 'Costo de Ventas', 'gasto', 'costo_ventas'),
    ('70', 'Ventas', 'ingreso', 'ingresos'),
    ('71', 'Variación de la Producción Almacenada', 'ingreso', 'otro_ingreso'),
    ('72', 'Producción de Activo Inmovilizado', 'ingreso', 'otro_ingreso'),
    ('73', 'Descuentos, Rebajas y Bonificaciones Obtenidos', 'ingreso', 'otro_ingreso'),
    ('74', 'Descuentos, Rebajas y Bonificaciones Concedidos', 'ingreso', 'otro_ingreso'),
    ('75', 'Otros Ingresos de Gestión', 'ingreso', 'otro_ingreso'),
    ('76', 'Ganancia por Medición de Activos No Financieros al Valor Razonable', 'ingreso', 'otro_ingreso'),
    ('77', 'Ingresos Financieros', 'ingreso', 'otro_ingreso'),
    ('78', 'Cargas Cubiertas por Provisiones', 'ingreso', 'otro_ingreso'),
    ('79', 'Cargas Imputables a Cuentas de Costos y Gastos', 'ingreso', 'otro_ingreso'),
)
